dist: bionic
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1.0

env:
  - COVERAGE=0 INSTALL_PROPHECY=1

matrix:
  include:
    - php: 7.4
      env: COVERAGE=1 INSTALL_PROPHECY=1
    - php: 7.0
      dist: xenial
      env: INSTALL_PROPHECY=0
    - php: 7.1
      env: INSTALL_PROPHECY=0

before_script:
  - if [[ "$COVERAGE" -eq 0 ]]; then composer install; else composer require php-coveralls/php-coveralls --dev; fi
  - if [[ "$INSTALL_PROPHECY" -eq 1 ]]; then composer require phpspec/prophecy --dev; fi

script:
  - if [[ "$COVERAGE" -eq 0 ]]; then vendor/bin/phpunit; else mkdir -p build/logs; vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; fi

after_script:
  - if [[ "$COVERAGE" -gt 0 ]]; then vendor/bin/php-coveralls; fi
