language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

env: COVERAGE=0

matrix:
  include:
    - php: 7.4
      env: COVERAGE=1

before_script:
  - if [[ "$COVERAGE" -eq 0 ]]; then composer install; else composer require php-coveralls/php-coveralls --dev; fi

script:
  - if [[ "$COVERAGE" -eq 0 ]]; then vendor/bin/phpunit; else mkdir -p build/logs; vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; fi

after_script:
  - if [[ "$COVERAGE" -gt 0 ]]; then vendor/bin/php-coveralls; fi
